// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kwMXM3a-xShvUUla6RX6kIEnAVmwE54',
    appId: '1:73398556637:web:f9c89da7dc5b90834a0834',
    messagingSenderId: '73398556637',
    projectId: 'todo-app-75624',
    authDomain: 'todo-app-75624.firebaseapp.com',
    storageBucket: 'todo-app-75624.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5cyKNmQy2eB7FGLIt8PDPgMOr-XSmzk',
    appId: '1:73398556637:android:b4c97d07a352ef654a0834',
    messagingSenderId: '73398556637',
    projectId: 'todo-app-75624',
    storageBucket: 'todo-app-75624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQnzgKiWaejMp3WopqE-rLaP2nMmcuLQ',
    appId: '1:73398556637:ios:22330517647bef2e4a0834',
    messagingSenderId: '73398556637',
    projectId: 'todo-app-75624',
    storageBucket: 'todo-app-75624.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQnzgKiWaejMp3WopqE-rLaP2nMmcuLQ',
    appId: '1:73398556637:ios:8a808161f14667c54a0834',
    messagingSenderId: '73398556637',
    projectId: 'todo-app-75624',
    storageBucket: 'todo-app-75624.appspot.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
